require 'rake/testtask'

# $:.unshift File.join(File.dirname(__FILE__), "lib")
# $:.unshift File.join(File.dirname(__FILE__), "test")

Rake::TestTask.new do |t|
	t.libs << "test"
	t.test_files = FileList["test/carbon/*Test.rb"]
	t.verbose = true
end
